export const QUERY_KEYS = {
  MAIN_CAROUSEL_IMAGE: ['MAIN_CAROUSEL_IMAGE'],
  STRIP_BANNERS: ['STRIP_BANNERS'],
};

export const MAIN_CAROUSEL_OPTIONS = {
  AUTO_ROLLING_TIME: 5000,
  WIDTH: 3800,
  HEIGHT: 960,
  NAVIGATION_ICON_SIZE: 28,
  NAVIGATION_ICON_STROKE_WIDTH: 0.75,
};

export const STRIP_BANNER_OPTIONS = {
  AUTO_ROLLING_TIME: 5000,
  WIDTH: 3840,
  HEIGHT: 470,
};
